# Generated by Django 4.1.6 on 2023-02-06 11:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('todo_text', models.CharField(max_length=300)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'ordering': ['done', '-created'],
            },
        ),
    ]
