# Generated by Django 4.1.6 on 2023-02-08 07:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('todo_text', models.CharField(max_length=300)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['done', '-created'],
            },
        ),
    ]
